/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside.vue')['default']
    CardSlider: typeof import('./src/components/CardSlider.vue')['default']
    ChatGptSharewriter: typeof import('./src/components/ChatGptSharewriter.vue')['default']
    ChatGptSharewriterSmall: typeof import('./src/components/ChatGptSharewriterSmall.vue')['default']
    ChatGptTypewriter: typeof import('./src/components/ChatGptTypewriter.vue')['default']
    ChatGptTypewriterSmall: typeof import('./src/components/ChatGptTypewriterSmall.vue')['default']
    CollectItem: typeof import('./src/components/CollectItem.vue')['default']
    CollectItemSmall: typeof import('./src/components/CollectItemSmall.vue')['default']
    CustomSlider: typeof import('./src/components/CustomSlider.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    McdModal: typeof import('./src/components/McdModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
    VanCascader: typeof import('vant/es')['Cascader']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
